apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: grafana-sa-token-cluster
type: Opaque
stringData:
  token: "glsa_xxxxxxxxxxxx"
---
apiVersion: orgmapper.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  grafanaUrl: "https://grafana.example.com"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: grafana-sa-token-cluster
      key: token
