apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: grafana-sa-token
type: Opaque
stringData:
  token: "glsa_xxxxxxxxxxxx"
---
apiVersion: orgmapper.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: default
spec:
  grafanaUrl: "https://grafana.example.com"
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: grafana-sa-token
      key: token
